# docker-compose.yml for production host
version: '3.7'

services:
  web: 
    image: ${DOCKERHUB_USER}/c5kvs_web:${BUILD_TIMESTAMP}
    container_name: c5kvs_web
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      APP_SERVER: http://app:80

  app:
    image: ${DOCKERHUB_USER}/c5kvs_app:${BUILD_TIMESTAMP}
    container_name: c5kvs_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB: 0

  db:
    image: redis:5.0.6-alpine3.10
    container_name: c5kvs_db
    restart: unless-stopped
    volumes:
      - c5kvs_redis_volume:/data

volumes:
  c5kvs_redis_volume:
    driver: local 