# docker-compose.yml for build/test host
version: '3.7'

services:
  appserver:
    build:
      context: ./app
      dockerfile: Dockerfile
      image: mykvsapp:${BUILD_NUMBER}
    restart: always
    depends_on:
      - redis
    ports:
      - 8000-8100:80
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  redis:
    image: redis:5.0.6-alpine3.10
    restart: always
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
    driver: local 

