# docker-compose.yml for build/test host
version: '3.7'

services:

  selenium_chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    container_name: mykvs_selenium_chrome
    depends_on:
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444

  selenium_hub:
    image: selenium/hub:3.141.59-vanadium
    container_name: mykvs_selenium_hub
    ports:
      - 4444:4444

  # WebTest: Webフロントのテスト
  # 必要な静的なファイルを取得できるかチェック
  # Seleniumを使って、GUI操作のテストをする
  webtest:
    build:
      context: ./webtest
      dockerfile: Dockerfile
    image: mykvs_webtest  
    container_name: mykvs_webtest
    restart: always
    depends_on:
      - web
      - selenium_hub
    tty: true
    volumes:
      - ./webtest/images:/test/images/
    environment:
      WEB_HOST: web
      WEB_PORT: 80
      SELENIUM_HUB_HOST: selenium_hub
      SELENIUM_HUB_PORT: 4444

  # AppTest: REST API Test
  # Appにたいして、REST APIのリクエストを投げて、
  # 期待されるレスポンスが得れるかテストする
  apptest:
    build:
      context: ./apptest
      dockerfile: Dockerfile
    image: mykvs_apptest
    container_name: mykvs_apptest
    restart: always
    depends_on:
      - app
    tty: true
    environment:
      APP_HOST: app
      APP_PORT: 80
      
  # Web: Static and Reverse Proxy
  # HTMLなどの静的なファイルの処理
  # /api/v1/宛の通信はappserverに流す
  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: mykvs_web
    container_name: mykvs_web
    restart: always
    depends_on:
      - app
    ports:
      - 8000-8100:80

  # App: Rest API for Key Value Store
  # Webから流されたREST APIの処理を担当
  # APIを解釈し、裏のRedis(DB)を操作する。
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: mykvs_app
    container_name: mykvs_app
    restart: always
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB: 0

  # DB: Key Value Store
  # AppからのRedis操作への応答
  # Redisをそのまま利用
  db:
    image: redis:5.0.6-alpine3.10
    restart: always
    container_name: mykvs-db
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
    driver: local 

