#
# Please add 
# content of Jenkins's "~/.ssh/id_rsa.pub" 
# to 
# build/production docker host's "~/.ssh/authorized_keys".
# after deploying Jenkins.
#
# Jenkins will use docker/docker-compose command for remote docker hosts.
# It will fail without key-based authentication.
#

version: '3.7'

services:
  jenkins: 
    build:
      context: ./
      dockerfile: Dockerfile
    image: myjenkins
    container_name: myjenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_volume:/data
    environment:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"

volumes:
  myjenkins_volume:
    driver: local